[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mujoco_wasm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
configure = { cmd = [
  "emcmake",
  "cmake",
  "-GNinja",
  "-DCMAKE_BUILD_TYPE=Release",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-S",
  ".",
  "-B",
  "build/",
] }
generate-templates = { cmd = [
  "python",
  "src/parse_mjxmacro.py",
  "build/_deps/mujoco-src",
], depends-on = [
  "configure",
] }
build = { cmd = "cmake --build build/", depends-on = ["generate-templates"] }
install = { cmd = "cmake --install build/", depends-on = ["build"] }

[dependencies]
emscripten = ">=3.1.58,<4"
cmake = ">=3.31.5,<4"
python = "==3.11"
